live_config_reload = true
working_directory = "/home/tameem/"

# args = ["-l", "-c", "tmux attach || tmux"]
[shell]
program = "/usr/bin/zsh"
args = ["-l", "-c", "tmux"]

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
dynamic_padding = false
title = ""
opacity = 0.9
option_as_alt = "Both"


[font]
size = 13

# [font.offset]
# y = 1
# x = 0
# [font.glyph_offset]
# x = 0
# y = 1

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"


# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
# background = '#222436'
foreground = '#c8d3f5'

#[colors.cursor]
#cursor = '#c8d3f5'
#text = '#222436'

# Normal colors
[colors.normal]
black = '#1b1d2b'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#828bb8'

# Bright colors
[colors.bright]
black = '#444a73'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#c8d3f5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#000000'

[[colors.indexed_colors]]
index = 17
color = '#c53b53'





